name: Deploy code
on:
  workflow_dispatch:
    inputs:
      migrate:
        description: "Run migration"
        required: true
        type: boolean
        default: false

jobs:
  lint:
    name: Lint JavaScript/TypeScript code
    runs-on: self-hosted
    steps:
      - name: Lint
        run: echo "Lint"

  migration:
    name: Run database migration
    runs-on: self-hosted
    needs: lint
    # only run when migrate=true
    if: ${{ github.event.inputs.migrate == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Migrate
        run: echo "Running migrations…"

  deploy:
    name: Deploy ${{ github.event.inputs.target }}
    runs-on: self-hosted
    needs:
      - lint
      - migration
    environment: ${{ github.event.inputs.target }}
    # run if migration succeeded OR was skipped (i.e. migrate=false)
    if: ${{ needs.migration.result == 'success' || needs.migration.result == 'skipped' }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.target }}…"
