name: Deploy code
on:
  workflow_dispatch:
    inputs:
      migrate:
        description: "Run migration"
        required: true
        type: boolean
        default: false

jobs:
  migration:
    name: Run database migration
    runs-on: ubuntu-latest
    # only run when migrate=true
    if: ${{ github.event.inputs.migrate == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Migrate
        run: echo "Running migrations…" && sleep 30

  deploy:
    name: Deploy ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    needs: [ migration ]
    environment: ${{ github.event.inputs.target }}
    # if: ${{ needs.migration.result == 'success' || needs.migration.result != 'skipped'  }}
    steps:
      - name: Deploy
        run: echo "ABCD - ${{ needs.migration.result }}…"
