name: Deploy code
on:
  workflow_dispatch:
    inputs:
      migrate:
        description: "Run migration"
        required: true
        type: boolean
        default: false

jobs:
  lint:
    name: Lint JavaScript/TypeScript code
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "Lint"

  migration:
    name: Run database migration
    runs-on: ubuntu-latest
    needs: lint
    # only run when migrate=true
    if: ${{ github.event.inputs.migrate == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Migrate
        run: echo "Running migrations…" && sleep 30

  deploy:
    name: Deploy ${{ github.event.inputs.target }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - migration
    environment: ${{ github.event.inputs.target }}
    if: ${{ !failure() }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ needs.migration.result }}…"
